#! /bin/sh

echo "----| Is this a linux or mac installation?"
read SYS
if [ "$SYS" = "linux" -o "$SYS" = "mac" ]; then
    echo "----| Running with system set to $SYS"
else
    echo "----| Unrecognized system, please specify linux or mac"
    return 1
fi

CURR_DIR=$PWD

mkdir -p ~/github.com
mkdir -p ~/bin

mv ~/.vimrc ~/.vimrc_old
mv ~/.vim ~/.vim_old

mv ~/.gitconfig ~/.gitconfig_old
mv ~/.tmux.conf ~/.tmux.conf_old

ln -s $CURR_DIR/vim/vimrc ~/.vimrc
ln -s $CURR_DIR/vim ~/.vim

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

echo "source-file $CURR_DIR/tmux/tmux.conf" >> ~/.tmux.conf
echo "source-file $CURR_DIR/tmux/"$SYS"_tmux.conf" >> ~/.tmux.conf

ln -s $CURR_DIR/git/gitconfig ~/.gitconfig

mv ~/.zshrc ~/.zshrc_old
SHRC=~/.zshrc
mv ~/.bashrc ~/.bashrc_old

if which zsh; then
    echo "---| zsh present, would you like to install oh-my-zsh? (Y or N)"
    read INSTALL_OH_MY_ZSH
    if [ "$INSTALL_OH_MY_ZSH" = "Y" ]; then
        echo "---| kill the zsh process after it completes to continue running bootstrap script!"
        sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
        sed -i 's/robbyrussell/dallas/' ~/.zshrc
    fi
fi

echo "----| Creating symlinks to ~/bin/ scripts"
for f in $CURR_DIR/bin/*
do
    ln -s $f ~/bin/.
done

echo "----| Adding aliases and setting path in $SHRC"
echo "source $CURR_DIR/zsh/bin-include" >> $SHRC
echo "source $CURR_DIR/zsh/aliases" >> $SHRC
echo "source $CURR_DIR/zsh/"$SYS"_aliases" >> $SHRC
