#! /bin/sh

echo "----| Is this a linux or mac installation?"
read SYS
if [ "$SYS" = "linux" -o "$SYS" = "mac" ]; then
    echo "----| Running with system set to $SYS"
else
    echo "----| Unrecognized system, please specify linux or mac"
    return 1
fi

CURR_DIR=$PWD

mkdir -p ~/github.com
mkdir -p ~/bin

mv ~/.gitconfig ~/.gitconfig_old
mv ~/.tmux.conf ~/.tmux.conf_old

echo "source-file $CURR_DIR/tmux/tmux.conf" >> ~/.tmux.conf
echo "source-file $CURR_DIR/tmux/"$SYS"_tmux.conf" >> ~/.tmux.conf

ln -s $CURR_DIR/git/gitconfig ~/.gitconfig

SHRC=~/.zshrc
sed -i 's/robbyrussell/dallas/' ~/.zshrc

echo "----| Creating symlinks to ~/bin/ scripts"
for f in $CURR_DIR/bin/*
do
    ln -s $f ~/bin/.
done

echo "----| Adding aliases and setting path in $SHRC"
echo "source $CURR_DIR/zsh/bin-include" >> $SHRC
echo "source $CURR_DIR/zsh/aliases" >> $SHRC
echo "source $CURR_DIR/zsh/gnome-vim" >> $SHRC
echo "source $CURR_DIR/zsh/helpers" >> $SHRC
echo "source $CURR_DIR/zsh/"$SYS"_aliases" >> $SHRC
echo "source $CURR_DIR/jrnl/jrnl_aliases" >> $SHRC
